-- AURA — Kartotéka klientů pro kadeřnický salon
-- Produkční schéma pro Synology MariaDB 10

SET NAMES utf8mb4;

-- ─── Klienti ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients` (
    `id`         INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `full_name`  VARCHAR(120)     NOT NULL,
    `phone`      VARCHAR(30)      DEFAULT NULL,
    `status`     ENUM('active','inactive','vip') NOT NULL DEFAULT 'active',
    `notes`      TEXT             DEFAULT NULL,
    `tags`       JSON             DEFAULT NULL,
    `created_at` DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_full_name` (`full_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── Návštěvy ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `client_visits` (
    `id`             INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `client_id`      INT UNSIGNED     NOT NULL,
    `visit_date`     DATE             NOT NULL,
    `service_name`   VARCHAR(200)     NOT NULL DEFAULT '',
    `color_formula`  JSON             DEFAULT NULL,
    `note`           TEXT             DEFAULT NULL,
    `price`          DECIMAL(10,2)    DEFAULT NULL,
    `billing_status` ENUM('unpaid','paid','complimentary') NOT NULL DEFAULT 'unpaid',
    `billing_amount` DECIMAL(10,2)    DEFAULT NULL,
    `billing_change` DECIMAL(10,2)    DEFAULT NULL,
    `created_at`     DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_client_id` (`client_id`),
    KEY `idx_visit_date` (`visit_date`),
    CONSTRAINT `fk_visit_client`
        FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── Katalog produktů ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `price_list_items` (
    `id`            INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `title`         VARCHAR(200)     NOT NULL,
    `category`      VARCHAR(80)      DEFAULT NULL,
    `series`        VARCHAR(100)     DEFAULT NULL,
    `volume`        VARCHAR(50)      DEFAULT NULL,
    `default_price` DECIMAL(8,2)     DEFAULT NULL,
    `is_active`     TINYINT(1)       NOT NULL DEFAULT 1,
    `is_retail`     TINYINT(1)       NOT NULL DEFAULT 0,
    `created_at`    DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_title` (`title`),
    KEY `idx_category` (`category`),
    KEY `idx_series` (`series`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── Prodeje (retail) ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `retail_sales` (
    `id`         INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `client_id`  INT UNSIGNED     DEFAULT NULL,
    `visit_id`   INT              DEFAULT NULL,
    `items`      JSON             NOT NULL,
    `total`      DECIMAL(10,2)    NOT NULL DEFAULT 0.00,
    `note`       TEXT             DEFAULT NULL,
    `created_at` DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_client_id` (`client_id`),
    KEY `idx_created_at` (`created_at`),
    KEY `idx_visit_id` (`visit_id`),
    CONSTRAINT `fk_sale_client`
        FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── Číselníky ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `code_lists` (
    `id`         INT              NOT NULL AUTO_INCREMENT,
    `type`       VARCHAR(50)      NOT NULL,
    `name`       VARCHAR(255)     NOT NULL,
    `icon`       VARCHAR(50)      DEFAULT NULL,
    `sort_order` INT              DEFAULT 0,
    `created_at` TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── Štítky ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `tags` (
    `id`         INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `name`       VARCHAR(100)     NOT NULL,
    `color`      VARCHAR(7)       NOT NULL DEFAULT '#a78bfa',
    `sort_order` INT              NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── Přiřazení štítků ke klientům ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `client_tags` (
    `client_id`  INT UNSIGNED     NOT NULL,
    `tag_id`     INT UNSIGNED     NOT NULL,
    PRIMARY KEY (`client_id`, `tag_id`),
    KEY `tag_id` (`tag_id`),
    CONSTRAINT `client_tags_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE CASCADE,
    CONSTRAINT `client_tags_ibfk_2` FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── Poznámky ke klientům ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `client_notes` (
    `id`         INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `client_id`  INT UNSIGNED     NOT NULL,
    `content`    TEXT             NOT NULL,
    `created_at` DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_client_notes_client` (`client_id`),
    CONSTRAINT `fk_notes_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── Denní uzávěrky ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `daily_closings` (
    `id`              INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `closing_date`    DATE             NOT NULL,
    `services_total`  DECIMAL(10,2)    NOT NULL DEFAULT 0.00,
    `products_total`  DECIMAL(10,2)    NOT NULL DEFAULT 0.00,
    `total`           DECIMAL(10,2)    NOT NULL DEFAULT 0.00,
    `visits_count`    INT              NOT NULL DEFAULT 0,
    `sales_count`     INT              NOT NULL DEFAULT 0,
    `note`            TEXT             DEFAULT NULL,
    `created_at`      DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_closing_date` (`closing_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── Nastavení aplikace ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `app_settings` (
    `setting_key`   VARCHAR(50)  NOT NULL,
    `setting_value` TEXT         DEFAULT NULL,
    PRIMARY KEY (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Při prvním spuštění se zobrazí formulář pro vytvoření přihlašovacích údajů

-- ─── Výchozí data — Materiály z barvy_loreal.csv (339 položek) ─────────────────
INSERT INTO `price_list_items` (`title`, `category`, `series`, `volume`, `default_price`, `is_active`, `is_retail`) VALUES
('Inoa 1', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 2', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 2.10', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 3', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 4', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 4.0', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 4.15', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 4.20', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 4.26', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 4.3', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 4.35', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 4.45', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 4.56', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 4.62', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 4.8', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.0', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.1', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.12', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.15', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.17', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.18', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.25', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.26', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.3', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.32', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.35', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.4', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.5', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.60', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.62', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 5.8', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.0', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.1', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.11', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.13', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.23', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.3', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.32', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.34', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.35', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.40', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.45', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.46', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.66', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 6.8', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.0', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.1', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.11', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.13', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.18', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.23', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.3', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.31', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.34', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.35', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.4', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.43', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.44', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 7.8', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 8', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 8.0', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 8.1', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 8.11', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 8.12', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 8.13', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 8.21', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 8.23', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 8.3', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 8.31', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 8.34', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 9', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 9.0', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 9.1', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 9.11', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 9.12', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 9.13', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 9.2', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 9.3', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 9.31', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 10', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 10.1', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 10.11', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 10.12', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa 10.21', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa CLEAR', 'Barva', 'Inoa', NULL, NULL, 1, 0),
('Inoa Boosters Blue', 'Barva', 'Inoa Boosters', NULL, NULL, 1, 0),
('Inoa Boosters Green', 'Barva', 'Inoa Boosters', NULL, NULL, 1, 0),
('Inoa Boosters Violet', 'Barva', 'Inoa Boosters', NULL, NULL, 1, 0),
('Majirel 1', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 2.10', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 3', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 4', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 4.0', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 4.15', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 4.20', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 4.3', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 4.35', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 4.45', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 4.56', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 4.62', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 4.8', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.0', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.1', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.12', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.15', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.18', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.26', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.3', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.32', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.35', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.4', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.5', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.52', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.60', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 5.8', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 6', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 6.0', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 6.1', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 6.13', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 6.23', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 6.3', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 6.32', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 6.34', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 6.35', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 6.45', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 6.46', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 6.64', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 6.66', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.0', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.1', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.11', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.12', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.13', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.18', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.23', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.3', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.31', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.35', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.4', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.40', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.43', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.44', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.45', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 7.8', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 8', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 8.0', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 8.1', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 8.11', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 8.13', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 8.21', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 8.3', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 8.31', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 8.34', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 8.43', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 9', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 9.03', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 9.1', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 9.11', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 9.12', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 9.13', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 9.22', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 9.3', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 9.31', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 10', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 10.1', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 10.12', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 10.21', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel 10.31', 'Barva', 'Majirel', NULL, NULL, 1, 0),
('Majirel Boosters Contrast', 'Barva', 'Majirel Boosters', NULL, NULL, 1, 0),
('Majirel Boosters Magenta', 'Barva', 'Majirel Boosters', NULL, NULL, 1, 0),
('Majirel Boosters Orange', 'Barva', 'Majirel Boosters', NULL, NULL, 1, 0),
('Majirel Boosters Red', 'Barva', 'Majirel Boosters', NULL, NULL, 1, 0),
('Majirel Cool Cover 4', 'Barva', 'Majirel Cool Cover', NULL, NULL, 1, 0),
('Majirel Cool Cover 5', 'Barva', 'Majirel Cool Cover', NULL, NULL, 1, 0),
('Majirel Cool Cover 5.1', 'Barva', 'Majirel Cool Cover', NULL, NULL, 1, 0),
('Majirel Cool Cover 5.17', 'Barva', 'Majirel Cool Cover', NULL, NULL, 1, 0),
('Majirel Cool Cover 6', 'Barva', 'Majirel Cool Cover', NULL, NULL, 1, 0),
('Majirel Cool Cover 6.1', 'Barva', 'Majirel Cool Cover', NULL, NULL, 1, 0),
('Majirel Cool Cover 6.17', 'Barva', 'Majirel Cool Cover', NULL, NULL, 1, 0),
('Majirel Cool Cover 7', 'Barva', 'Majirel Cool Cover', NULL, NULL, 1, 0),
('Majirel Cool Cover 7.1', 'Barva', 'Majirel Cool Cover', NULL, NULL, 1, 0),
('Majirel Cool Cover 8', 'Barva', 'Majirel Cool Cover', NULL, NULL, 1, 0),
('Majirel Cool Cover 8.1', 'Barva', 'Majirel Cool Cover', NULL, NULL, 1, 0),
('Majirel Cool Cover 9', 'Barva', 'Majirel Cool Cover', NULL, NULL, 1, 0),
('Majirel High Lift ASH+', 'Barva', 'Majirel High Lift', NULL, NULL, 1, 0),
('Majirel High Lift ASH VIOLET', 'Barva', 'Majirel High Lift', NULL, NULL, 1, 0),
('Majirel High Lift NEUTR', 'Barva', 'Majirel High Lift', NULL, NULL, 1, 0),
('Majirel High Lift VIOLET', 'Barva', 'Majirel High Lift', NULL, NULL, 1, 0),
('Majirel High Lift BEIGE', 'Barva', 'Majirel High Lift', NULL, NULL, 1, 0),
('Majirel High Lift 900S', 'Barva', 'Majirel High Lift', NULL, NULL, 1, 0),
('Majirel High Lift 901S', 'Barva', 'Majirel High Lift', NULL, NULL, 1, 0),
('DIAcolor 1', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 3', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 4', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 4.12', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 4.15', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 4.20', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 4.45', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 4.62', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 5', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 5.1', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 5.18', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 5.3', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 5.35', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 5.4', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 5.5', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 5.71', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 5.8', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 6', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 6.1', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 6.12', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 6.23', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 6.3', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 6.31', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 6.34', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 6.35', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 6.45', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 6.60', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 6.8', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 6.84', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 7', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 7.1', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 7.13', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 7.18', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 7.32', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 7.44', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 7.8', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 8', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 8.1', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 8.13', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 8.2', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 8.23', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 8.3', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 8.31', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 8.34', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 8.43', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 9', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 9.1', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 9.13', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor 9.82', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIAcolor CLEAR', 'Barva', 'DIAcolor', NULL, NULL, 1, 0),
('DIALight 4', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 5', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 5.11', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 5.8', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 6', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 6.1', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 6.11', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 6.23', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 6.3', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 6.35', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 6.45', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 6.64', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 6.66', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 6.8', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 7', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 7.01', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 7.12', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 7.18', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 7.23', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 7.3', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 7.31', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 7.4', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 7.43', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 8', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 8.1', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 8.11', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 8.13', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 8.21', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 8.23', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 8.24', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 8.28', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 8.3', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 8.34', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 8.43', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 9', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 9.01', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 9.02', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 9.03', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 9.11', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 9.12', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 9.13', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 9.2', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 9.21', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 9.3', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 9.82', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 10.01', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 10.02', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 10.12', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 10.13', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 10.18', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 10.21', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 10.22', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 10.23', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 10.24', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 10.32', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 10.82', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight 0 (Clear)', 'Přeliv', 'DIALight', NULL, NULL, 1, 0),
('DIALight Boosters Blue', 'Přeliv', 'DIALight Boosters', NULL, NULL, 1, 0),
('DIALight Boosters Orange', 'Přeliv', 'DIALight Boosters', NULL, NULL, 1, 0),
('DIALight Boosters Red', 'Přeliv', 'DIALight Boosters', NULL, NULL, 1, 0),
('DIALight Boosters Violet', 'Přeliv', 'DIALight Boosters', NULL, NULL, 1, 0),
('DIALight Boosters Yellow', 'Přeliv', 'DIALight Boosters', NULL, NULL, 1, 0),
('DIALight Boostery Červený', 'Přeliv', 'DIALight Boostery', NULL, NULL, 1, 0),
('DIALight Boostery Duhový', 'Přeliv', 'DIALight Boostery', NULL, NULL, 1, 0),
('DIALight Boostery Kovový', 'Přeliv', 'DIALight Boostery', NULL, NULL, 1, 0),
('DIALight Boostery Měděný', 'Přeliv', 'DIALight Boostery', NULL, NULL, 1, 0),
('DIALight Boostery Popelavý', 'Přeliv', 'DIALight Boostery', NULL, NULL, 1, 0),
('DIALight Boostery Zlatý', 'Přeliv', 'DIALight Boostery', NULL, NULL, 1, 0),
('Blond Studio Platinum Plus-7', 'Melír', 'Blond Studio', NULL, NULL, 1, 0),
('Blond Studio Multi Techniques-8', 'Melír', 'Blond Studio', NULL, NULL, 1, 0),
('Blond Studio 9', 'Melír', 'Blond Studio', NULL, NULL, 1, 0),
('Blond Studio Bonder Inside-9', 'Melír', 'Blond Studio', NULL, NULL, 1, 0),
('Blond Studio Fialový zesvětlující balzám-8', 'Melír', 'Blond Studio', NULL, NULL, 1, 0),
('Oxidant Inoa Oleo Vyvíječ 3% (10 Vol)', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Oxidant Inoa Oleo Vyvíječ 6% (20 Vol)', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Oxidant Inoa Oleo Vyvíječ 9% (30 Vol)', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Oxidant Majirel Ox. Krém 3.75%', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Oxidant Majirel Ox. Krém 6%', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Oxidant Majirel Ox. Krém 9%', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Oxidant DIA Vyvíječ 6 Vol (1.8%)', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Oxidant DIA Vyvíječ 9 Vol (2.7%)', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Oxidant DIA Vyvíječ 15 Vol (4.5%)', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Oxidant Nutri Vyvíječ 6% (20 Vol)', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Oxidant Nutri Vyvíječ 9% (30 Vol)', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Oxidant Nutri Vyvíječ 12% (40 Vol)', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Oxidant Blond Studio Oleo Vyvíječ 6% (20 Vol)', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Oxidant Blond Studio Oleo Vyvíječ 9% (30 Vol)', 'Oxy', 'Oxidant', NULL, NULL, 1, 0),
('Preparace Dulcia Advanced 0', 'Trvalá', 'Preparace', NULL, NULL, 1, 0),
('Preparace Dulcia Advanced 1', 'Trvalá', 'Preparace', NULL, NULL, 1, 0),
('Preparace Dulcia Advanced 2', 'Trvalá', 'Preparace', NULL, NULL, 1, 0),
('Preparace Dulcia Advanced 3', 'Trvalá', 'Preparace', NULL, NULL, 1, 0),
('Ostatní Efassor sáček', 'Speciál', 'Ostatní', NULL, NULL, 1, 0),
('Ostatní Efassor ubrousky', 'Speciál', 'Ostatní', NULL, NULL, 1, 0);

-- ─── Výchozí data — Retail produkty z produkty_loreal.csv (107 položek) ───────
INSERT INTO `price_list_items` (`title`, `category`, `series`, `volume`, `default_price`, `is_active`, `is_retail`) VALUES
('Absolut Repair Maska', 'Retail', 'Absolut Repair', '250 ml', NULL, 1, 1),
('Absolut Repair Maska zlatá', 'Retail', 'Absolut Repair', '250 ml', NULL, 1, 1),
('Absolut Repair Olej', 'Retail', 'Absolut Repair', '90 ml', NULL, 1, 1),
('Absolut Repair Pěna', 'Retail', 'Absolut Repair', '200 ml', NULL, 1, 1),
('Absolut Repair Šampon', 'Retail', 'Absolut Repair', '500 ml', NULL, 1, 1),
('Absolut Repair Šampon', 'Retail', 'Absolut Repair', '300 ml', NULL, 1, 1),
('Absolut Repair Molecular Bezoplachová maska', 'Retail', 'Absolut Repair Molecular', '100 ml', NULL, 1, 1),
('Absolut Repair Molecular Discovery Box Mini Duo Kit', 'Retail', 'Absolut Repair Molecular', '1 set', NULL, 1, 1),
('Absolut Repair Molecular Discovery Box Mini Trio Kit', 'Retail', 'Absolut Repair Molecular', '1 set', NULL, 1, 1),
('Absolut Repair Molecular Dvoufázový olej', 'Retail', 'Absolut Repair Molecular', '90 ml', NULL, 1, 1),
('Absolut Repair Molecular Maska', 'Retail', 'Absolut Repair Molecular', '250 ml', NULL, 1, 1),
('Absolut Repair Molecular Sérum', 'Retail', 'Absolut Repair Molecular', '250 ml', NULL, 1, 1),
('Absolut Repair Molecular Šampon', 'Retail', 'Absolut Repair Molecular', '500 ml', NULL, 1, 1),
('Absolut Repair Molecular Šampon', 'Retail', 'Absolut Repair Molecular', '300 ml', NULL, 1, 1),
('Aminexil Advanced Aminexil kúra', 'Retail', 'Aminexil Advanced', '10x6 ml', NULL, 1, 1),
('Aminexil Advanced Aminexil kúra', 'Retail', 'Aminexil Advanced', '42x6 ml', NULL, 1, 1),
('Aminexil Advanced Anti Hair Loss Activator', 'Retail', 'Aminexil Advanced', '90 ml', NULL, 1, 1),
('Blondifier Cool péče', 'Retail', 'Blondifier', '200 ml', NULL, 1, 1),
('Blondifier Gloss šampon', 'Retail', 'Blondifier', '500 ml', NULL, 1, 1),
('Blondifier Gloss šampon', 'Retail', 'Blondifier', '300 ml', NULL, 1, 1),
('Blondifier Maska', 'Retail', 'Blondifier', '250 ml', NULL, 1, 1),
('Blondifier Pěna', 'Retail', 'Blondifier', '200 ml', NULL, 1, 1),
('Curl Expression Curls reviver', 'Retail', 'Curl Expression', '190 ml', NULL, 1, 1),
('Curl Expression Definition activator', 'Retail', 'Curl Expression', '250 ml', NULL, 1, 1),
('Curl Expression Long lasting moisturizer', 'Retail', 'Curl Expression', '200 ml', NULL, 1, 1),
('Curl Expression Maska', 'Retail', 'Curl Expression', '250 ml', NULL, 1, 1),
('Curl Expression Pěna 10 v 1', 'Retail', 'Curl Expression', '250 ml', NULL, 1, 1),
('Curl Expression Šampon', 'Retail', 'Curl Expression', '500 ml', NULL, 1, 1),
('Curl Expression Šampon', 'Retail', 'Curl Expression', '300 ml', NULL, 1, 1),
('Liss Unlimited Maska', 'Retail', 'Liss Unlimited', '250 ml', NULL, 1, 1),
('Liss Unlimited Šampon', 'Retail', 'Liss Unlimited', '500 ml', NULL, 1, 1),
('Liss Unlimited Šampon', 'Retail', 'Liss Unlimited', '300 ml', NULL, 1, 1),
('Liss Unlimited Sérum', 'Retail', 'Liss Unlimited', '125 ml', NULL, 1, 1),
('Metal Detox Discovery Box Mini Duo Kit', 'Retail', 'Metal Detox', '1 set', NULL, 1, 1),
('Metal Detox Discovery Box Mini Trio Kit', 'Retail', 'Metal Detox', '1 set', NULL, 1, 1),
('Metal Detox Krém', 'Retail', 'Metal Detox', '100 ml', NULL, 1, 1),
('Metal Detox Maska', 'Retail', 'Metal Detox', '250 ml', NULL, 1, 1),
('Metal Detox Olej', 'Retail', 'Metal Detox', '50 ml', NULL, 1, 1),
('Metal Detox Šampon', 'Retail', 'Metal Detox', '500 ml', NULL, 1, 1),
('Metal Detox Šampon', 'Retail', 'Metal Detox', '300 ml', NULL, 1, 1),
('Pro Longer Krém', 'Retail', 'Pro Longer', '150 ml', NULL, 1, 1),
('Pro Longer Maska', 'Retail', 'Pro Longer', '250 ml', NULL, 1, 1),
('Pro Longer Péče', 'Retail', 'Pro Longer', '500 ml', NULL, 1, 1),
('Pro Longer Péče', 'Retail', 'Pro Longer', '200 ml', NULL, 1, 1),
('Pro Longer Šampon', 'Retail', 'Pro Longer', '500 ml', NULL, 1, 1),
('Pro Longer Šampon', 'Retail', 'Pro Longer', '300 ml', NULL, 1, 1),
('Scalp Advanced Dermo Regulator šampon', 'Retail', 'Scalp Advanced', '500 ml', NULL, 1, 1),
('Scalp Advanced Dermo Regulator šampon', 'Retail', 'Scalp Advanced', '300 ml', NULL, 1, 1),
('Scalp Advanced Dermo Purifier šampon', 'Retail', 'Scalp Advanced', '500 ml', NULL, 1, 1),
('Scalp Advanced Dermo Purifier šampon', 'Retail', 'Scalp Advanced', '300 ml', NULL, 1, 1),
('Scalp Advanced Dermo Clarifier šampon', 'Retail', 'Scalp Advanced', '500 ml', NULL, 1, 1),
('Scalp Advanced Dermo Clarifier šampon', 'Retail', 'Scalp Advanced', '300 ml', NULL, 1, 1),
('Scalp Advanced Intense Soother', 'Retail', 'Scalp Advanced', '200 ml', NULL, 1, 1),
('Scalp Advanced 2 in 1 Clay', 'Retail', 'Scalp Advanced', '250 ml', NULL, 1, 1),
('Serioxyl Advanced Bodyfying šampon', 'Retail', 'Serioxyl Advanced', '500 ml', NULL, 1, 1),
('Serioxyl Advanced Bodyfying šampon', 'Retail', 'Serioxyl Advanced', '300 ml', NULL, 1, 1),
('Serioxyl Advanced Density Activator', 'Retail', 'Serioxyl Advanced', '90 ml', NULL, 1, 1),
('Silver Péče', 'Retail', 'Silver', '200 ml', NULL, 1, 1),
('Silver Šampon', 'Retail', 'Silver', '500 ml', NULL, 1, 1),
('Silver Šampon', 'Retail', 'Silver', '300 ml', NULL, 1, 1),
('Vitamino Color Maska', 'Retail', 'Vitamino Color', '250 ml', NULL, 1, 1),
('Vitamino Color Péče', 'Retail', 'Vitamino Color', '500 ml', NULL, 1, 1),
('Vitamino Color Péče', 'Retail', 'Vitamino Color', '200 ml', NULL, 1, 1),
('Vitamino Color Šampon', 'Retail', 'Vitamino Color', '500 ml', NULL, 1, 1),
('Vitamino Color Šampon', 'Retail', 'Vitamino Color', '300 ml', NULL, 1, 1),
('Vitamino Color Sprej 10 v 1', 'Retail', 'Vitamino Color', '190 ml', NULL, 1, 1),
('Vitamino Color Spectrum Bezoplachové sérum', 'Retail', 'Vitamino Color Spectrum', '50 ml', NULL, 1, 1),
('Vitamino Color Spectrum Intenzivní péče', 'Retail', 'Vitamino Color Spectrum', '200 ml', NULL, 1, 1),
('Vitamino Color Spectrum Maska', 'Retail', 'Vitamino Color Spectrum', '250 ml', NULL, 1, 1),
('Vitamino Color Spectrum Neutraliz. šampon fialový', 'Retail', 'Vitamino Color Spectrum', '500 ml', NULL, 1, 1),
('Vitamino Color Spectrum Neutraliz. šampon modrý', 'Retail', 'Vitamino Color Spectrum', '500 ml', NULL, 1, 1),
('Vitamino Color Spectrum Neutraliz. šampon zelený', 'Retail', 'Vitamino Color Spectrum', '500 ml', NULL, 1, 1),
('Vitamino Color Spectrum Neutraliz. šampon zelený', 'Retail', 'Vitamino Color Spectrum', '300 ml', NULL, 1, 1),
('Vitamino Color Spectrum Šampon', 'Retail', 'Vitamino Color Spectrum', '500 ml', NULL, 1, 1),
('Vitamino Color Spectrum Šampon', 'Retail', 'Vitamino Color Spectrum', '300 ml', NULL, 1, 1),
('Air Light Pro Fén Air Light Pro', 'Elektro', 'Air Light Pro', '1 ks', NULL, 1, 1),
('SteamPod SteamPod 3.0', 'Elektro', 'SteamPod', '1 ks', NULL, 1, 1),
('SteamPod SteamPod 4.0', 'Elektro', 'SteamPod', '1 ks', NULL, 1, 1),
('SteamPod SteamPod 4 Meteora', 'Elektro', 'SteamPod', '1 ks', NULL, 1, 1),
('SteamPod Profesionální vyhlazující péče', 'Retail', 'SteamPod', '50 ml', NULL, 1, 1),
('Hair Touch Up Černá 1-3', 'Sprej', 'Hair Touch Up', '75 ml', NULL, 1, 1),
('Hair Touch Up Hnědá 3-5', 'Sprej', 'Hair Touch Up', '75 ml', NULL, 1, 1),
('Hair Touch Up Mahagon 5-6', 'Sprej', 'Hair Touch Up', '75 ml', NULL, 1, 1),
('Hair Touch Up Světle hnědá 5-6', 'Sprej', 'Hair Touch Up', '75 ml', NULL, 1, 1),
('Hair Touch Up Tmavá blond 6-7', 'Sprej', 'Hair Touch Up', '75 ml', NULL, 1, 1),
('Hair Touch Up Zlatá blond 7-9', 'Sprej', 'Hair Touch Up', '75 ml', NULL, 1, 1),
('Homme Clay', 'Styling', 'Homme', '50 ml', NULL, 1, 1),
('Infinium Infinium Pure Extra Strong', 'Lak', 'Infinium', '300 ml', NULL, 1, 1),
('Infinium Infinium Pure Soft', 'Lak', 'Infinium', '300 ml', NULL, 1, 1),
('Infinium Infinium Pure Strong', 'Lak', 'Infinium', '300 ml', NULL, 1, 1),
('Tecni.art All-in-1 Performer', 'Styling', 'Tecni.art', '190 ml', NULL, 1, 1),
('Tecni.art Anti Frizz', 'Lak', 'Tecni.art', '250 ml', NULL, 1, 1),
('Tecni.art Fix Design', 'Retail', 'Tecni.art', '1000 ml', NULL, 1, 1),
('Tecni.art Fix Design', 'Retail', 'Tecni.art', '200 ml', NULL, 1, 1),
('Tecni.art Fix Max', 'Gel', 'Tecni.art', '200 ml', NULL, 1, 1),
('Tecni.art Fix Paste', 'Pasta', 'Tecni.art', '75 ml', NULL, 1, 1),
('Tecni.art Flex Blowdry', 'Styling', 'Tecni.art', '150 ml', NULL, 1, 1),
('Tecni.art Flex Curl Bounce', 'Styling', 'Tecni.art', '150 ml', NULL, 1, 1),
('Tecni.art Flex Depolish', 'Pasta', 'Tecni.art', '100 ml', NULL, 1, 1),
('Tecni.art Flex Liss Control', 'Styling', 'Tecni.art', '150 ml', NULL, 1, 1),
('Tecni.art Flex Pli', 'Styling', 'Tecni.art', '190 ml', NULL, 1, 1),
('Tecni.art Flex Waves', 'Styling', 'Tecni.art', '150 ml', NULL, 1, 1),
('Tecni.art Flex Web', 'Styling', 'Tecni.art', '190 ml', NULL, 1, 1),
('Tecni.art Volume Extra Full', 'Pěna', 'Tecni.art', '250 ml', NULL, 1, 1),
('Tecni.art Volume Dust', 'Pudr', 'Tecni.art', '7 g', NULL, 1, 1),
('Tecni.art Volume Panache', 'Styling', 'Tecni.art', '250 ml', NULL, 1, 1),
('Tecni.art Volume Rootlift', 'Pěna', 'Tecni.art', '250 ml', NULL, 1, 1);
